In [1]:
import numpy as np

In [2]:
# R = matrix to be factorized. size n x m 
# P = initial matrix. size n x k 
# Q = initial matrix. size m x k 
# K = number of latent features 
# steps = maximum number of steps to perform optimization 
# alpha = learning rate 
# beta = regularization parameter 

In [9]:
# R = np.array([[5,3,0,1],[4,0,0,1],[1,1,0,5],[1,0,0,4],[0,1,5,4]])
# N = len(R)
# M = len(R[0])
# K = 2

# P = np.random.rand(N,K)
# Q = np.random.rand(M,K)

# steps = 5000
# alpha = 0.0002
# beta = 0.02

# Q = np.transpose(Q)
# for step in range(steps):
#     for row in range(len(R)):
#         for col in range(len(R[row])):
#             #main matrix R is searched at every iteration so we only take into consideration the populated cells 
#             if R[row][col] > 0:
#                 #dot product of P and Q are subtracted from original matrix to find the error 
#                 #minimize until we approach the minimum
#                 eij = R[row][col]-np.dot(P[row,:],Q[:,col])
#                 for k in range(K):
#                     #calculate the gradient of P and Q, and update 
#                     P[row][k] = P[row][k] + alpha*(2*eij*Q[k][col]-beta*P[row][k])
#                     Q[k][col] = Q[k][col] + alpha*(2*eij*P[row][k]-beta*Q[k][col])
#     #eR = np.dot(P,Q)
#     #add regularization parameter, beta, to avoid obtaining large numbers for R 
#     e = 0
#     for row in range(len(R)):
#         for col in range(len(R[row])):
#             if R[row][col] > 0:
#                 e = e+pow(R[row][col]-np.dot(P[row,:],Q[:,col]),2)
#                 for k in range(K):
#                     e = e +(beta/2)*(pow(P[row][k],2)+pow(Q[k][col],2))
#     #if error is small enough break 
#     if e <0.001:
#         break 
# nr = np.dot(P,Q)
# print(nr)



[[5.00363976 2.90998183 4.92843088 0.99767828]
 [3.95604794 2.30734352 4.06332327 0.99621578]
 [1.08534912 0.78251928 4.88420956 4.96237627]
 [0.95689534 0.67706025 3.98224941 3.97214209]
 [2.00113242 1.27979304 4.89562907 4.03709523]]


# Matrix Factorization Function

In [10]:
def matrix_factorization(R,P,Q,K,steps,alpha,beta):
    Q = np.transpose(Q)
    for step in range(steps):
        for row in range(len(R)):
            for col in range(len(R[row])):
                #main matrix R is searched at every iteration so we only take into consideration the populated cells 
                if R[row][col] > 0:
                    #dot product of P and Q are subtracted from original matrix to find the error 
                    #minimize until we approach the minimum
                    eij = R[row][col]-np.dot(P[row,:],Q[:,col])
                    for k in range(K):
                        #calculate the gradient of P and Q, and update 
                        P[row][k] = P[row][k] + alpha*(2*eij*Q[k][col]-beta*P[row][k])
                        Q[k][col] = Q[k][col] + alpha*(2*eij*P[row][k]-beta*Q[k][col])
        #eR = np.dot(P,Q)
        #add regularization parameter, beta, to avoid obtaining large numbers for R 
        e = 0
        for row in range(len(R)):
            for col in range(len(R[row])):
                if R[row][col] > 0:
                    e = e+pow(R[row][col]-np.dot(P[row,:],Q[:,col]),2)
                    for k in range(K):
                        e = e +(beta/2)*(pow(P[row][k],2)+pow(Q[k][col],2))
        #if error is small enough break 
        if e <0.001:
            break 
    return P,Q
#nr = np.dot(P,Q)
#print(nr)

# Change Inputs and Run Function 

In [14]:
R = np.array([[4,3,0,1,2],[5,0,0,1,0],[1,2,1,5,4],[1,0,0,4,0],[0,1,5,4,0],[5,5,0,0,1]])
N = len(R)
M = len(R[0])
K = 3
P = np.random.rand(N,K)
Q = np.random.rand(M,K)

steps = 10000
alpha = 0.0002
beta = 0.02

nP,nQ = matrix_factorization(R,P,Q,K,steps,alpha,beta)
final = np.dot(nP,nQ)
print(final)

[[ 3.77124722  3.26713026  4.97258642  1.12664765  1.78845154]
 [ 4.98615936  4.67765184  6.0361502   0.96203012  2.13993669]
 [ 1.04332951  1.93739921  0.99934294  4.948489    4.02390732]
 [ 1.00426094  1.24337301  1.57316389  3.98817962  3.11648187]
 [ 2.34043172  0.97901536  4.9920237   3.96632499  2.93579246]
 [ 5.12420249  4.7958313   5.91161108 -0.60895953  1.1114315 ]]
